// Create Warehouses
CREATE WAREHOUSE IMPORT_WH2
  WITH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  INITIALLY_SUSPENDED = TRUE;

  CREATE WAREHOUSE TRANSFORM_WH2
  WITH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  INITIALLY_SUSPENDED = TRUE;

  CREATE WAREHOUSE REPORTING_WH2
  WITH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 900
  MAX_CLUSTER_COUNT = 5
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = 'ECONOMY'
  INITIALLY_SUSPENDED = TRUE;

// Create Databases
CREATE DATABASE STAGING2;
CREATE DATABASE PROD2;

// Create Schemas
CREATE SCHEMA STAGING.RAW2;
CREATE SCHEMA STAGING.CLEAN2;
CREATE SCHEMA PROD.REPORTING2;

// Set Data Retention
ALTER SCHEMA STAGING.RAW2 SET DATA_RETENTION_TIME_IN_DAYS = 3;
ALTER SCHEMA STAGING.CLEAN2 SET DATA_RETENTION_TIME_IN_DAYS = 3;
ALTER SCHEMA PROD.REPORTING2 SET DATA_RETENTION_TIME_IN_DAYS = 90;

// Create Roles
CREATE ROLE IMPORT_ROLE2;
CREATE ROLE TRANSFORM_ROLE2;
CREATE ROLE REPORTING_ROLE2;

// Grant privileges to IMPORT_ROLE2
GRANT USAGE ON WAREHOUSE IMPORT_WH2 TO ROLE IMPORT_ROLE2;
GRANT USAGE ON DATABASE STAGING2 TO ROLE IMPORT_ROLE2;
GRANT USAGE ON SCHEMA STAGING.RAW2 TO ROLE IMPORT_ROLE2;
GRANT USAGE ON SCHEMA STAGING.CLEAN2 TO ROLE IMPORT_ROLE2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING.RAW2 TO ROLE IMPORT_ROLE2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING.CLEAN2 TO ROLE IMPORT_ROLE2;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA STAGING.RAW2 TO ROLE IMPORT_ROLE2;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA STAGING.CLEAN2 TO ROLE IMPORT_ROLE2;

// Grant privileges to TRANSFORM_ROLE2
GRANT USAGE ON WAREHOUSE TRANSFORM_WH2 TO ROLE TRANSFORM_ROLE2;
GRANT USAGE ON DATABASE STAGING2 TO ROLE TRANSFORM_ROLE2;
GRANT USAGE ON SCHEMA STAGING.CLEAN2 TO ROLE TRANSFORM_ROLE2;
GRANT USAGE ON DATABASE PROD2 TO ROLE TRANSFORM_ROLE2;
GRANT USAGE ON SCHEMA PROD.REPORTING2 TO ROLE TRANSFORM_ROLE2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING.CLEAN2 TO ROLE TRANSFORM_ROLE2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROD.REPORTING2 TO ROLE TRANSFORM_ROLE2;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA STAGING.CLEAN2 TO ROLE TRANSFORM_ROLE2;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PROD.REPORTING2 TO ROLE TRANSFORM_ROLE2;

// Grant privileges to REPORTING_ROLE2
GRANT USAGE ON WAREHOUSE REPORTING_WH2 TO ROLE REPORTING_ROLE2;
GRANT USAGE ON DATABASE PROD2 TO ROLE REPORTING_ROLE2;
GRANT USAGE ON SCHEMA PROD.REPORTING2 TO ROLE REPORTING_ROLE2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD.REPORTING2 TO ROLE REPORTING_ROLE2;

// Create Users
CREATE USER UserImport2 PASSWORD = 'UIPWD2'
  DEFAULT_ROLE = IMPORT_ROLE2
  DEFAULT_WAREHOUSE = IMPORT_WH2
  MUST_CHANGE_PASSWORD = TRUE;

 CREATE USER UserTransform2 PASSWORD = 'UTPWD2'
  DEFAULT_ROLE = TRANSFORM_ROLE2
  DEFAULT_WAREHOUSE = TRANSFORM_WH2
  MUST_CHANGE_PASSWORD = TRUE; 

  CREATE USER UserReporting2 PASSWORD = 'URPWD2'
  DEFAULT_ROLE = REPORTING_ROLE2
  DEFAULT_WAREHOUSE = REPORTING_WH2
  MUST_CHANGE_PASSWORD = TRUE;

// Assign Roles to Users
GRANT ROLE IMPORT_ROLE2 TO USER UserImport2;
GRANT ROLE TRANSFORM_ROLE2 TO USER UserTransform2;
GRANT ROLE REPORTING_ROLE2 TO USER UserReporting2;

// Create Resource Monitors
CREATE RESOURCE MONITOR IMPORT_MONITOR2 WITH CREDIT_QUOTA = 100;
CREATE RESOURCE MONITOR TRANSFORM_MONITOR2 WITH CREDIT_QUOTA = 100;
CREATE RESOURCE MONITOR REPORTING_MONITOR2 WITH CREDIT_QUOTA = 100;

// Assign Resource Monitors to Warehouses
ALTER WAREHOUSE IMPORT_WH2 SET RESOURCE_MONITOR = IMPORT_MONITOR2;
ALTER WAREHOUSE TRANSFORM_WH2 SET RESOURCE_MONITOR = TRANSFORM_MONITOR2;
ALTER WAREHOUSE REPORTING_WH2 SET RESOURCE_MONITOR = REPORTING_MONITOR2;